# Generated by Django 4.2.2 on 2023-07-07 06:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sale',
            managers=[
                ('reporting', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='purchaseline',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchaseline',
            old_name='compra',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='purchaseline',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
