# Generated by Django 4.2.2 on 2023-07-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_sale_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sale',
            managers=[
            ],
        ),
    ]
